server:
  port: 8888

compte:
  adasfa: asdfds

stockcode:
  balance:
    - 报告日期,ReportDate
    - 货币资金,MonetaryFund
    - 结算备付金,SettlementProvision


spring:
  profiles:
    include:
      shcode,szcode,shkccode,allcode